export PATH=~/aSk/bin:$PATH

shopt -s autocd # cd into dir without cd command

### Alias
alias ls="ls --color"
alias ll='ls --color -lrth'
alias cl='clear; ls --color -lrth'
alias tmux='tmux -2 -f ~/aSk/tmux.conf'

alias bashrc='vim ~/aSk/bashrc'
alias vimrc='vim ~/aSk/init.vim'
alias tmuxrc='vim ~/aSk/tmux.conf'

alias dot='cd ~/aSk/dotfiles'

function task(){
  if [ -z "$TMUX" ]; then
    tmux attach -t aSk || tmux new -s aSk
  fi
}

