// Code generated by scripts/gen-theme.sh from design/palette.toml. DO NOT EDIT.

package ui

// SolarizedLight is the solarized-light flavor.
func SolarizedLight() Theme {
	return Theme{
		Fg:       "#657b83",
		Muted:    "#93a1a1",
		Emphasis: "#586e75",
		Accent:   "#268bd2",
		SelBg:    "#eee8d5",
		Working:  "#2aa198",
		Asking:   "#b58900",
		Blocked:  "#dc322f",
		Done:     "#859900",
	}
}

// SolarizedDark is the solarized-dark flavor.
func SolarizedDark() Theme {
	return Theme{
		Fg:       "#839496",
		Muted:    "#586e75",
		Emphasis: "#93a1a1",
		Accent:   "#268bd2",
		SelBg:    "#073642",
		Working:  "#2aa198",
		Asking:   "#b58900",
		Blocked:  "#dc322f",
		Done:     "#859900",
	}
}

// CatppuccinLatte is the catppuccin-latte flavor.
func CatppuccinLatte() Theme {
	return Theme{
		Fg:       "#4c4f69",
		Muted:    "#8c8fa1",
		Emphasis: "#2e3047",
		Accent:   "#1e66f5",
		SelBg:    "#ccd0da",
		Working:  "#179299",
		Asking:   "#df8e1d",
		Blocked:  "#d20f39",
		Done:     "#40a02b",
	}
}

// CatppuccinMocha is the catppuccin-mocha flavor.
func CatppuccinMocha() Theme {
	return Theme{
		Fg:       "#cdd6f4",
		Muted:    "#6c7086",
		Emphasis: "#eef1fb",
		Accent:   "#89b4fa",
		SelBg:    "#313244",
		Working:  "#94e2d5",
		Asking:   "#fab387",
		Blocked:  "#f38ba8",
		Done:     "#a6e3a1",
	}
}

// ThemeByName resolves a flavor name, falling back to the default flavor.
func ThemeByName(name string) Theme {
	switch name {
	case "solarized-dark":
		return SolarizedDark()
	case "catppuccin-latte":
		return CatppuccinLatte()
	case "catppuccin-mocha":
		return CatppuccinMocha()
	default:
		return SolarizedLight()
	}
}
